"""Embeddings of effective models into second-quantized Hamiltonians.

Notation used in this module:

- *Source* is the effective model and *target* the Hamiltonian passed to
  `~pymablock.block_diagonalize`. The isometry W maps source states to target states.
- A *lattice* is the set of target occupations ``n = r + M q`` reached from one
  reference state ``r`` by the generator images. ``M`` is ``_occupation_matrix``,
  ``q`` are the source occupations (``_source_occupations``), ``n(q)`` is
  ``_target_of_source`` and ``q(n) = L (n - r)``, with ``L`` the left inverse of
  ``M``, is ``_source_of_target``.
- ``_target_numbers`` and ``_source_numbers`` are the placeholder symbols of the
  number operators inside NOF coefficients.
- A list of references gives one lattice per reference. The *frame* W is a matrix
  with one column per reference, placed in that reference's target row. Column j is
  ``T_j W_1``: the transfer operator ``T_j`` carries the first lattice onto
  lattice j, so every frame entry carries the first reference's symbolic embedding.
  ``_Lattice`` stores the compiled maps and algebra; ``Embedding`` owns the symbolic
  identity, ordered lattice collection, and frame.
- An *amplitude* is the matrix element of a ladder monomial between occupation
  states.
"""

from __future__ import annotations

from collections.abc import Callable, Hashable, Mapping, Sequence
from functools import cached_property, wraps
from typing import Self

import sympy
from sympy.physics.quantum.boson import BosonOp
from sympy.physics.quantum.fermion import FermionOp

from pymablock.number_ordered_form import (
    LadderOp,
    NumberOperator,
    NumberOrderedForm,
    OperatorType,
    _allowed_values_indicator,
    _number_operator_to_placeholder,
    _occupation_dimension,
    _operator_sort_key,
    find_operators,
    generator_types,
)

__all__ = ["Embedding"]


class _ReferenceRow(sympy.AtomicExpr):
    """A reference key distinct from every user symbol, including after pickling."""

    def _sympystr(self, _printer):
        return "Embedding.row"


def _cache_on_instance[Result](method: Callable[..., Result]) -> Callable[..., Result]:
    """Memoize a method with hashable positional arguments on its owning instance.

    Unlike a global method cache, this does not keep discarded embeddings alive.
    The wrapped methods accept positional arguments only.
    """

    @wraps(method)
    def cached(self: object, *args: Hashable) -> Result:
        memo = self.__dict__.setdefault("_memo_" + method.__name__, {})
        if args not in memo:
            memo[args] = method(self, *args)
        return memo[args]

    return cached


class Embedding(sympy.Expr):
    r"""Select the states of an effective model inside a second-quantized Hamiltonian.

    Below, *source* refers to the effective model, and *target* refers to the
    Hamiltonian passed to `~pymablock.block_diagonalize`. The embedding maps
    source states to target states. A generator mapping defines the source algebra;
    a reference list adds a matrix index labeling disjoint copies of that algebra.
    A mapping reference defines one occupation lattice; a list defines an ordered
    collection of disjoint lattices.

    Each source occupation state maps, up to a phase, to a single target occupation
    state. Generator images must have fixed, linearly independent occupation shifts,
    giving the affine map :math:`n = r + Mq`: ``q`` is the source occupation vector,
    ``r`` is the target reference, and the columns of ``M`` are the occupation
    increments generated by the adjoint images. Arbitrary superpositions of target
    occupation states are unsupported; a change of mode basis must be performed
    on the Hamiltonian before constructing the embedding.

    Pass the embedding as ``subspace_eigenvectors`` to
    `~pymablock.block_diagonalize` or `~pymablock.operator_to_BlockSeries`.
    Block 0 contains the embedded states and block 1 contains all other target
    states, which remain available for virtual transitions. See the
    :doc:`structured embeddings documentation <../structured_embeddings>` for
    requirements and examples with physical models.

    Parameters
    ----------
    generators : collections.abc.Mapping
        Maps each source lowering operator to a target expression. The keys may be
        ``SigmaMinus``, ``FermionOp``, ``BosonOp``, or ``LadderOp`` operators. A
        ``LadderOp`` key also needs an entry mapping its ``NumberOperator`` to a
        target expression, because its lowering operator does not determine it.
        Use an empty mapping to select finite reference states.
    reference : collections.abc.Mapping or collections.abc.Sequence
        A mapping declares every target operator and its occupation in
        the target state that represents the source state with all occupations and
        ``LadderOp`` indices equal to zero. Applying the adjoints of the target
        expressions to this state defines all other embedded states and their
        phases. ``LadderOp`` source operators also use the target expressions
        themselves to reach negative indices.

        A list declares one such reference per source matrix index. Each reference
        generates a copy of the source algebra; these lattices must be disjoint.
        With no generators, each copy is a single state. All references must use
        the same target operators. The optional ``Embedding.row`` dictionary key
        selects the target matrix row and defaults to zero. For a matrix Hamiltonian
        without operators, use ``[{}, {Embedding.row: 2}]``.

    Examples
    --------
    >>> import sympy
    >>> from sympy.physics.quantum.boson import BosonOp
    >>> from sympy.physics.quantum.pauli import SigmaMinus
    >>> from pymablock.number_ordered_form import NumberOperator
    >>> a, s = BosonOp("a"), SigmaMinus("s")

    Represent a spin by the two lowest levels of the oscillator ``a``:

    >>> embedding = Embedding({s: a}, reference={a: 0})
    >>> embedding.restrict(a).as_expr() == s
    True

    Select the three lowest levels as a finite matrix basis:

    >>> embedding = Embedding({}, reference=[{a: n} for n in range(3)])
    >>> embedding.restrict(NumberOperator(a)) == sympy.diag(0, 1, 2)
    True

    """

    row = _ReferenceRow()

    is_commutative = False

    # Construction and format boundaries.

    def __new__(
        cls,
        generators: Mapping,
        reference: Mapping | Sequence | None = None,
    ) -> Self:
        """Build the symbolic isometry and compile its occupation lattices."""
        references = _parse_references(reference)
        if not isinstance(generators, (Mapping, sympy.Dict)):
            raise TypeError("Generators must be a mapping")
        generators = sympy.Dict(generators)
        if isinstance(reference, (Mapping, sympy.Dict)):
            if references[0][0] != 0:
                raise ValueError(
                    "Nonzero reference matrix indices require a reference list"
                )
            states = references[0][1]
        else:
            states = sympy.Tuple(
                *(
                    sympy.Dict({Embedding.row: row, **dict(state)})
                    for row, state in references
                )
            )
        self = sympy.Expr.__new__(cls, generators, states)
        self._lattices = cls._build_lattices(generators, references)
        self._validate_disjointness()
        self._transfers = tuple(
            self._first_lattice._transfer(lattice) for _, lattice in self._lattices
        )
        return self

    @staticmethod
    def _build_lattices(generators: sympy.Dict, references: sympy.Tuple) -> tuple:
        """Compile each reference, sharing source occupation symbols across lattices."""
        lattices = []
        for row, reference in references:
            if lattices and set(reference) != set(lattices[0][1]._target_operators):
                raise ValueError("Every reference must declare the same target modes")
            shared = lattices[0][1]._source_occupations if lattices else None
            lattice = _Lattice(dict(generators), dict(reference), shared)
            lattices.append((int(row), lattice))
        return tuple(lattices)

    def _printed_arguments(self, printer) -> list[str]:
        """Print reconstructible public constructor arguments."""
        generators, reference = self.args
        if isinstance(reference, sympy.Tuple):
            reference = list(reference)
        keyword = r"\text{reference}" if printer.printmethod == "_latex" else "reference"
        return [printer._print(generators), f"{keyword}={printer._print(reference)}"]

    def _sympystr(self, printer) -> str:
        """Print the public constructor name."""
        return f"Embedding({', '.join(self._printed_arguments(printer))})"

    def _latex(self, printer) -> str:
        """Keep the public expression name in rendered equations."""
        arguments = ", ".join(self._printed_arguments(printer))
        return rf"\operatorname{{Embedding}}\left({arguments}\right)"

    def restrict(
        self, expression: sympy.Expr | sympy.MatrixBase
    ) -> NumberOrderedForm | sympy.MatrixBase:
        """Express a target operator in terms of the embedded states.

        The result contains the matrix elements of ``expression`` between embedded
        states, without perturbative corrections. Products are evaluated in the full
        target space before taking these matrix elements, so intermediate states
        outside the embedding contribute. For example, with ``{s: a}``,
        ``restrict(a * Dagger(a))`` is ``1 + N_s``, while
        ``restrict(a) * restrict(Dagger(a))`` is ``1 - N_s``.

        With a mapping reference, the result is a
        `~pymablock.number_ordered_form.NumberOrderedForm` in the source operators.
        It may contain products such as ``N_s * (1 - N_s)`` that vanish because
        fermion and spin occupations are 0 or 1; call ``simplify()`` to remove
        them. With a list of states, the result is a SymPy matrix in the order of
        the list, with source NOFs as entries when generators are supplied.
        Symbolic integer powers with known sign are supported for infinite source
        ladders when their induced shifts are provably integer. Undecidable shifts
        or finite-source bounds raise ``NotImplementedError``.
        """
        target = self._target_matrix(expression)
        w = self._retained_frame(target.rows)
        return self._format_output(w.adjoint() * target * w)

    def _target_matrix(
        self, expression: sympy.Expr | sympy.MatrixBase
    ) -> sympy.MatrixBase:
        """Parse a target operator, or a matrix of them, into a square matrix of NOFs."""
        if not isinstance(expression, sympy.MatrixBase):
            if any(row for row, _ in self._lattices):
                raise ValueError(
                    "Nonzero reference matrix indices require a matrix target"
                )
            expression = sympy.ImmutableMatrix([[expression]])
        elif isinstance(self.args[1], sympy.Dict):
            raise TypeError("Matrix targets require a list of reference states")
        if expression.rows != expression.cols:
            raise ValueError("Target matrices must be square")
        if any(row >= expression.rows for row, _ in self._lattices):
            raise ValueError("Reference matrix index lies outside the target matrix")
        return sympy.ImmutableSparseMatrix(
            expression.applyfunc(self._first_lattice._parse_target)
        )

    def _format_output(
        self, result: sympy.MatrixBase
    ) -> NumberOrderedForm | sympy.MatrixBase:
        """Return operator-free entries as scalars, and a mapping reference's entry alone."""
        result = result.applyfunc(
            lambda value: (
                value.terms.get((), sympy.S.Zero)
                if isinstance(value, NumberOrderedForm)
                and not value.operators
                and value.embedding is None
                else value
            )
        )
        if isinstance(self.args[1], sympy.Dict):
            return result[0, 0]
        return result

    # The full frame: indexed lattices and block matrices.

    @property
    def _first_lattice(self) -> _Lattice:
        """Return the compiled lattice at the first reference."""
        return self._lattices[0][1]

    @cached_property
    def _first_embedding(self) -> Embedding:
        """Return the symbolic single-reference isometry used by frame attachments."""
        if isinstance(self.args[1], sympy.Dict):
            return self
        reference = dict(self.args[1][0])
        reference.pop(Embedding.row)
        # Share validated data; reconstruction still compiles from the public args.
        embedding = sympy.Expr.__new__(type(self), self.args[0], sympy.Dict(reference))
        embedding._lattices = ((0, self._first_lattice),)
        embedding._transfers = (self._first_lattice._target_identity,)
        return embedding

    @_cache_on_instance
    def _retained_frame(self, rows: int) -> sympy.MatrixBase:
        """Return the frame W: one column ``T_j W_1`` per reference, in its target row."""
        w = sympy.zeros(rows, len(self._lattices))
        for col, ((row, _), transfer) in enumerate(zip(self._lattices, self._transfers)):
            w[row, col] = self._first_embedding._attach(transfer, 1)
        return sympy.ImmutableMatrix(w)

    @_cache_on_instance
    def _complement_frame(self, rows: int) -> sympy.MatrixBase:
        """Return Q = 1 - W W† when a complement block is needed."""
        w = self._retained_frame(rows)
        return sympy.eye(rows) - w * w.adjoint()

    @property
    def _column_states(self) -> tuple:
        """Return the target row and occupations ``n(q)`` of each frame column."""
        return tuple((row, lattice._target_of_source) for row, lattice in self._lattices)

    def _validate_disjointness(self) -> None:
        """Test the unique possible source displacement between same-row lattices."""
        first = self._first_lattice
        for i, (row, lattice) in enumerate(self._lattices):
            for other_row, other in self._lattices[:i]:
                if row != other_row:
                    continue
                delta = sympy.Matrix(lattice._reference_state) - sympy.Matrix(
                    other._reference_state
                )
                displacement = first._occupation_left_inverse * delta
                if first._occupation_matrix * displacement != delta:
                    continue
                if all(
                    d.is_Integer and (size is None or abs(d) < size)
                    for d, size in zip(displacement, first._source_dimensions)
                ):
                    raise ValueError("Reference lattices overlap")

    def _attach(self, value: NumberOrderedForm, side: int) -> NumberOrderedForm:
        """Represent ``value W`` for side +1, or ``W† value`` for side -1."""
        if not isinstance(self.args[1], sympy.Dict):
            raise TypeError("Reference-list embeddings require a matrix frame")
        value = value._expand_operators(self._first_lattice._target_operators)
        return NumberOrderedForm(
            value.operators, value.args[1], self, side, validate=False
        )


class _Lattice:
    """Compiled occupation map and operator algebra for one reference state.

    Instances are derived data, not symbolic isometries. Embedding constructor
    arguments determine their maps, phases, and instance-owned caches.
    """

    def __init__(
        self,
        generators: Mapping,
        reference: Mapping,
        source_occupations: tuple[sympy.Symbol, ...] | None = None,
    ) -> None:
        """Compile and validate the affine occupation map."""
        self._target_operators, self._reference_state = _ordered_reference_state(
            reference
        )
        numbers = {
            op: value
            for op, value in generators.items()
            if isinstance(op, NumberOperator)
        }
        operators = tuple(op for op in generators if op not in numbers)
        if not all(isinstance(op, generator_types) for op in operators):
            raise TypeError("Keys must be source lowering generators or ladder numbers")
        if any(not op.is_annihilation for op in operators):
            raise ValueError("Source generators must be lowering operators")
        operators = tuple(sorted(operators, key=_operator_sort_key))
        self._source_operators = operators
        self._source_dimensions = tuple(map(_occupation_dimension, operators))
        if source_occupations is None:
            source_occupations = tuple(
                sympy.Dummy(
                    f"source_{i}",
                    integer=True,
                    **({} if isinstance(op, LadderOp) else {"nonnegative": True}),
                )
                for i, op in enumerate(operators)
            )
        self._source_occupations = source_occupations
        images, shifts = [], []
        for op in operators:
            image = self._parse_target(generators[op])
            if len(image.terms) != 1 or not any(shift := next(iter(image.terms))):
                raise ValueError(
                    f"Image of {op} must change target occupations by one nonzero shift"
                )
            parity = sum(
                power
                for target, power in zip(self._target_operators, shift, strict=True)
                if isinstance(target, FermionOp)
            )
            if parity % 2 != isinstance(op, FermionOp):
                raise ValueError("Generator images must preserve fermionic parity")
            images.append(image)
            shifts.append(shift)
        self._generator_images = tuple(images)
        self._occupation_matrix = sympy.Matrix(
            len(self._target_operators), len(operators), lambda i, j: shifts[j][i]
        )
        if self._occupation_matrix.rank() != len(operators):
            raise ValueError("Generator shifts must be independent")
        matrix = self._occupation_matrix
        self._occupation_left_inverse = (matrix.T * matrix).inv() * matrix.T
        self._source_of_target = tuple(
            self._occupation_left_inverse
            * (sympy.Matrix(self._target_numbers) - sympy.Matrix(self._reference_state))
        )
        self._target_of_source = tuple(
            origin + sum(matrix[i, j] * q for j, q in enumerate(self._source_occupations))
            for i, origin in enumerate(self._reference_state)
        )
        self._validate_domains()
        self._validate_generator_algebra()
        self._phase = self._reference_phase()
        expected_numbers = {
            NumberOperator(op) for op in operators if isinstance(op, LadderOp)
        }
        if set(numbers) != expected_numbers:
            raise ValueError(
                "Supply the independent number image for each source LadderOp"
            )
        for op, number in numbers.items():
            index = next(
                i for i, source in enumerate(operators) if NumberOperator(source) == op
            )
            form = self._parse_target(number)
            if any(any(powers) for powers in form.terms):
                raise ValueError("A ladder number image must be occupation diagonal")
            expression = form.terms.get((0,) * len(self._target_operators), sympy.S.Zero)
            expression = self._evaluate_numbers(expression, self._target_of_source)
            self._require_vanishing(
                expression - self._source_occupations[index],
                f"Ladder number image {op} must count from the source reference index zero",
            )

    def _parse_target(self, expression: sympy.Expr) -> NumberOrderedForm:
        """Parse a target expression using the modes declared in the reference."""
        if isinstance(expression, NumberOrderedForm):
            return expression._expand_operators(self._target_operators)
        modes = self._target_operators
        expression = sympy.sympify(expression)
        if set(find_operators(expression)) - set(modes):
            raise ValueError("Every target mode must be declared in the reference")
        return NumberOrderedForm.from_expr(expression, operators=modes)

    @cached_property
    def _target_numbers(self) -> tuple[sympy.Symbol, ...]:
        """Return scalar number symbols in target mode order."""
        return tuple(
            _number_operator_to_placeholder(NumberOperator(op))
            for op in self._target_operators
        )

    @cached_property
    def _source_numbers(self) -> tuple[sympy.Symbol, ...]:
        """Return scalar number symbols in source mode order."""
        return tuple(
            _number_operator_to_placeholder(NumberOperator(op))
            for op in self._source_operators
        )

    @cached_property
    def _target_zero(self) -> NumberOrderedForm:
        """Return zero carrying the target operator basis."""
        return NumberOrderedForm(self._target_operators, {}, validate=False)

    @cached_property
    def _target_identity(self) -> NumberOrderedForm:
        """Return the identity in the target operator basis."""
        modes = self._target_operators
        return NumberOrderedForm(modes, {(0,) * len(modes): sympy.S.One}, validate=False)

    @cached_property
    def _source_zero(self) -> NumberOrderedForm:
        """Return zero carrying the source operator basis."""
        return NumberOrderedForm(self._source_operators, {}, validate=False)

    def _evaluate_numbers(
        self, expression: sympy.Expr, occupations: Sequence[int | sympy.Expr]
    ) -> sympy.Expr:
        """Evaluate a target number coefficient at the supplied occupations."""
        return expression.xreplace(
            dict(zip(self._target_numbers, occupations, strict=True))
        )

    def _validate_domains(self) -> None:
        """Check target occupation bounds over the full source occupation domain.

        Use each affine map's minimum and maximum, rather than enumerating states.
        Raise ValueError if a generator can overfill or underfill a target mode.
        """
        for i, op in enumerate(self._target_operators):
            lower = upper = self._reference_state[i]
            for coefficient, source, size in zip(
                self._occupation_matrix.row(i),
                self._source_operators,
                self._source_dimensions,
                strict=True,
            ):
                if not coefficient:
                    continue
                if size is None:
                    if isinstance(source, LadderOp):
                        lower, upper = -sympy.oo, sympy.oo
                    elif coefficient > 0:
                        upper = sympy.oo
                    else:
                        lower = -sympy.oo
                else:
                    lower += min(0, coefficient) * (size - 1)
                    upper += max(0, coefficient) * (size - 1)
            if not isinstance(op, LadderOp) and lower < 0:
                raise ValueError("Generators leave the physical target occupation domain")
            if _occupation_dimension(op) is not None and upper >= _occupation_dimension(
                op
            ):
                raise ValueError("Generators overfill a target spin or fermion")

    def _require_vanishing(self, expression: sympy.Expr, context: str) -> None:
        """Require an expression to vanish for all source occupations of the lattice.

        Reduce binary polynomials modulo n² - n before testing zero. A nonzero result
        raises ValueError; an undecidable one raises NotImplementedError.
        """
        binary = tuple(
            q
            for q, size in zip(self._source_occupations, self._source_dimensions)
            if size == 2
        )
        expression = sympy.expand(expression)
        for q in binary:
            if q in expression.free_symbols and expression.is_polynomial(q):
                expression = sympy.rem(expression, q**2 - q, q)
        if (
            expression != 0
            and expression.free_symbols <= set(binary)
            and expression.is_polynomial(*binary)
        ):
            raise ValueError(f"{context}; residual: {expression}")
        residual = sympy.simplify(expression)
        if residual == 0:
            return
        message = f"{context}; residual: {residual}"
        if residual.is_zero is False:
            raise ValueError(message)
        raise NotImplementedError(f"Cannot establish {message}")

    def _validate_generator_algebra(self) -> None:
        """Check local norms and graded commutation on the retained lattice.

        The occupation boundaries fix the vacuum and binary truncation. Norms
        then fix the same-mode algebra; pairwise lowering relations also fix
        the mixed adjoint relations by reversing an edge of each lattice square.
        """
        weights = [
            _matrix_element(image, self._target_of_source)
            for image in self._generator_images
        ]
        coordinates = self._source_occupations
        active = {
            q: sympy.S.One if size == 2 else q + 1
            for q, size in zip(coordinates, self._source_dimensions)
        }
        for i, q in enumerate(coordinates):
            norm = (
                weights[i] * sympy.conjugate(weights[i])
                - self._lowering_amplitude(i) ** 2
            )
            self._require_vanishing(
                norm.xreplace({q: active[q]}),
                "Generator images must produce normalized source states",
            )
            for j, other in enumerate(coordinates[:i]):
                sign = (
                    -1
                    if all(
                        isinstance(self._source_operators[k], FermionOp) for k in (i, j)
                    )
                    else 1
                )
                relation = weights[j] * weights[i].xreplace(
                    {other: other - 1}
                ) - sign * weights[i] * weights[j].xreplace({q: q - 1})
                self._require_vanishing(
                    relation.xreplace({q: active[q], other: active[other]}),
                    "Generator images must obey the source algebra",
                )

    @_cache_on_instance
    def _source_amplitude(self, powers: tuple[int, ...]) -> sympy.Expr:
        """Return the source ladder amplitude of a shift at symbolic occupations."""
        term = NumberOrderedForm(
            self._source_operators, {powers: sympy.S.One}, validate=False
        )
        return _matrix_element(term, self._source_occupations)

    def _lowering_amplitude(self, index: int) -> sympy.Expr:
        """Return the source lowering amplitude for mode ``index`` at symbolic numbers."""
        return self._source_amplitude(
            tuple(int(i == index) for i in range(len(self._source_operators)))
        )

    def _reference_phase(self) -> sympy.Expr:
        """Return the phase relating normalized target and source occupation states.

        Compare target and source lowering amplitudes in a fixed creation order.
        Infinite modes require a number-independent ratio; otherwise raise
        NotImplementedError. The reference state's phase is one.
        """
        phase = sympy.S.One
        for i, (image, q, size) in enumerate(
            zip(
                self._generator_images,
                self._source_occupations,
                self._source_dimensions,
                strict=True,
            )
        ):
            ratio = self._lowering_amplitude(i) / _matrix_element(
                image, self._target_of_source
            )
            ratio = ratio.xreplace(
                dict.fromkeys(self._source_occupations[:i], sympy.S.Zero)
            )
            if size is None:
                ratio = sympy.simplify(ratio)
                if ratio.free_symbols.intersection(self._source_occupations):
                    raise NotImplementedError(
                        "Infinite source generators require a constant phase relative to their ladder weights"
                    )
                phase *= ratio**q
            else:
                phase *= 1 - q + q * sympy.simplify(ratio.xreplace({q: sympy.S.One}))
        return sympy.factor(phase)

    @_cache_on_instance
    def _source_shift(
        self, target_shift: tuple[sympy.Expr, ...]
    ) -> tuple[sympy.Expr, ...] | None:
        """Return the induced source shift, or None if compression annihilates it.

        The target shift must lie in the occupation map's image and correspond to
        integer source steps within each finite mode's range.
        """
        target = sympy.Matrix(target_shift)
        result = self._occupation_left_inverse * target
        residual = self._occupation_matrix * result - target
        if any(value.is_zero is False for value in residual):
            return None
        if any(value.is_zero is not True for value in residual):
            raise NotImplementedError(
                "Cannot establish whether the shift leaves the lattice"
            )
        for value, size in zip(result, self._source_dimensions, strict=True):
            if value.is_integer is False:
                return None
            if value.is_integer is not True:
                raise NotImplementedError("Cannot establish an integer source shift")
            if size is not None:
                outside = abs(value) >= size
                if outside is sympy.S.true:
                    return None
                if outside is not sympy.S.false:
                    raise NotImplementedError("Cannot establish a finite source shift")
        return tuple(result)

    @_cache_on_instance
    def _restrict_term(
        self, target_shift: tuple[int, ...], target_amplitude: sympy.Expr
    ) -> NumberOrderedForm:
        """Restrict one target term, given its amplitude on retained states.

        Convert its shift and amplitude to source occupations. Spectator numbers
        stay symbolic; a term that leaves the lattice gives zero.
        """
        powers = self._source_shift(target_shift)
        if powers is None:
            return self._source_zero
        shifted = {q: q - p for q, p in zip(self._source_occupations, powers)}
        # The phase has unit modulus on the retained domain. Its ratio cancels
        # unchanged factors without expanding binary occupation identities.
        amplitude = (
            target_amplitude
            / self._source_amplitude(powers)
            * self._phase
            / self._phase.xreplace(shifted)
        )
        # NOF coefficients sit between creation and annihilation operators.
        # A binary transition fixes its input occupation; spectators stay symbolic.
        initial = {
            q: sympy.Integer(1 if p > 0 else 0) if p and size == 2 else n + max(p, 0)
            for q, n, p, size in zip(
                self._source_occupations,
                self._source_numbers,
                powers,
                self._source_dimensions,
            )
        }
        coefficient = sympy.factor_terms(amplitude.xreplace(initial))
        return NumberOrderedForm(
            self._source_operators, {powers: coefficient}, validate=False
        )

    @_cache_on_instance
    def _restrict(self, target: NumberOrderedForm) -> NumberOrderedForm:
        """Return ``W† target W`` by translating each term to the source algebra."""
        result = self._source_zero
        for shift, (_, amplitude) in target.act(self._target_of_source).items():
            result += self._restrict_term(shift, amplitude)
        return result

    @cached_property
    def _projector(self) -> NumberOrderedForm:
        """Return ``W W†``, the target-space projector onto retained states.

        Scalar indicators enforce the affine occupation constraints and each source
        mode's allowed numbers. No target occupation states are enumerated.
        """
        numbers = self._target_numbers
        offsets = sympy.Matrix(numbers) - sympy.Matrix(self._reference_state)
        spectra = [
            (sympy.expand(normal.dot(offsets)), (0,))
            for normal in self._occupation_matrix.T.nullspace()
        ]
        source = self._source_of_target
        physical = {
            n: sympy.Dummy(integer=True, nonnegative=True)
            for target, n in zip(self._target_operators, numbers)
            if not isinstance(target, LadderOp)
        }
        for q, op, size in zip(source, self._source_operators, self._source_dimensions):
            if (
                isinstance(op, BosonOp)
                and q.xreplace(physical).is_nonnegative is not True
            ):
                raise NotImplementedError(
                    "This bosonic embedding requires an occupation inequality"
                )
            spectra.append((q, range(size) if size is not None else sympy.S.Integers))
        indicator = sympy.prod(
            _allowed_values_indicator(q, spectrum) for q, spectrum in spectra
        )
        return NumberOrderedForm(
            self._target_operators, {(0,) * len(self._target_operators): indicator}
        )._linearize_binary_operators()

    @_cache_on_instance
    def _lift(self, value: NumberOrderedForm) -> NumberOrderedForm:
        """Represent a source operator in target space, as ``W value W†``.

        Replace source generators and numbers by their target images, then project
        both sides onto the retained space.
        """
        if value.is_zero:
            return self._target_zero
        value = value._expand_operators(self._source_operators)
        coordinates = dict(
            zip(value._number_operator_placeholders, self._source_of_target)
        )
        result = self._target_zero
        for powers, coefficient in value.terms.items():
            term = NumberOrderedForm(
                self._target_operators,
                {(0,) * len(self._target_operators): coefficient.xreplace(coordinates)},
                validate=False,
            )
            # Match NOF ordering: creations, coefficient, reversed annihilations.
            # NOF multiplication supplies the graded signs of fermion images.
            for image, power in reversed(list(zip(self._generator_images, powers))):
                if power > 0:
                    term = term * image**power
            for image, power in reversed(list(zip(self._generator_images, powers))):
                if power < 0:
                    term = image.adjoint() ** (-power) * term
            result += term
        return self._projector * result * self._projector

    def _transfer(self, lattice: _Lattice) -> NumberOrderedForm:
        """Return the transfer operator T carrying this lattice onto ``lattice``.

        T is the ladder monomial for the reference difference, normalized and with the
        phase that makes ``T W`` equal to the other lattice's isometry.
        """
        powers = tuple(
            a - b for a, b in zip(self._reference_state, lattice._reference_state)
        )
        if not any(powers):
            return self._target_identity
        if any(p and any(self._occupation_matrix.row(i)) for i, p in enumerate(powers)):
            raise NotImplementedError(
                "Reference translations along generator-moving modes are not supported"
            )
        monomial = NumberOrderedForm(self._target_operators, {powers: sympy.S.One})
        weight = _matrix_element(monomial, self._target_of_source)
        # Physical domains at both references ensure this shift never annihilates.
        coefficient = sympy.simplify(lattice._phase / self._phase / weight)
        # The coefficient sits after annihilation: recover incoming occupations.
        incoming = {n: n + max(p, 0) for n, p in zip(self._target_numbers, powers)}
        coefficient = coefficient.xreplace(
            {
                q: coordinate.xreplace(incoming)
                for q, coordinate in zip(self._source_occupations, self._source_of_target)
            }
        )
        return NumberOrderedForm(
            self._target_operators, {powers: coefficient}, validate=False
        )


def _parse_references(reference: Mapping | Sequence | None) -> sympy.Tuple:
    """Normalize reference declarations to target-row/occupation pairs."""
    if reference is None:
        raise TypeError("Specify reference occupations for the embedding")
    if isinstance(reference, (Mapping, sympy.Dict)):
        reference = (reference,)
    states = []
    for state in reference:
        if not isinstance(state, (Mapping, sympy.Dict)):
            raise TypeError("References must be occupation mappings")
        occupations = dict(state)
        row = occupations.pop(Embedding.row, 0)
        row = sympy.sympify(row)
        if not row.is_Integer or row < 0:
            raise ValueError("Matrix basis indices must be nonnegative integers")
        states.append(sympy.Tuple(row, sympy.Dict(occupations)))
    if not states:
        raise ValueError("Specify at least one reference state")
    return sympy.Tuple(*states)


def _matrix_element(term: NumberOrderedForm, occupations: Sequence) -> sympy.Expr:
    """Return the matrix element of a single-term NOF, or zero if it annihilates."""
    actions = term.act(occupations)
    if not actions:
        return sympy.S.Zero
    ((_, matrix_element),) = actions.values()
    return matrix_element


def _ordered_reference_state(
    reference: Mapping[OperatorType, int | sympy.Integer],
) -> tuple[tuple[OperatorType, ...], tuple[sympy.Integer, ...]]:
    """Validate a product state and return modes and numbers in canonical order.

    Require lowering-mode keys and integer occupations in each mode's domain.
    Fermionic matrix elements use this ordering for their parity signs.
    """
    if not isinstance(reference, Mapping) or not all(
        isinstance(op, generator_types) and op.is_annihilation for op in reference
    ):
        raise TypeError("Reference keys must be target lowering generators")
    operators = tuple(sorted(reference, key=_operator_sort_key))
    state = tuple(sympy.sympify(reference[op]) for op in operators)
    for op, n in zip(operators, state, strict=True):
        size = _occupation_dimension(op)
        if (
            not n.is_Integer
            or (not isinstance(op, LadderOp) and n < 0)
            or (size is not None and n >= size)
        ):
            raise ValueError("Reference occupations lie outside the target algebra")
    return operators, state
