"""Structured second-quantized subspace embeddings.

The objects in this module are algebraic counterparts of the matrices accepted
through ``subspace_eigenvectors``.  They describe an isometry ``W`` from a
retained Hilbert space into a source Fock space without enumerating the source
space.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import cached_property
from itertools import product
from typing import TYPE_CHECKING, TypeAlias

import sympy
from sympy.physics.quantum.fermion import FermionOp

from pymablock.number_ordered_form import generator_types

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable, Mapping, Sequence
    from typing import Any

__all__ = [
    "FermionEmbedding",
    "OccupationEmbedding",
    "OperatorEmbedding",
    "fermion_embedding",
    "levels",
    "occupation_embedding",
]

OccupationState: TypeAlias = tuple[int, ...]


class _CoordinateArithmetic:
    """Arithmetic shared by finite coordinates and their expressions."""

    def _binary(self, other, operation: Callable, symbol: str):
        other = _as_coordinate_expression(other)
        return CoordinateExpression(
            lambda values: operation(self.evaluate(values), other.evaluate(values)),
            _unique((*self.coordinates, *other.coordinates)),
            f"({self!s} {symbol} {other!s})",
        )

    def __add__(self, other):
        return self._binary(other, lambda left, right: left + right, "+")

    def __radd__(self, other):
        return _as_coordinate_expression(other).__add__(self)

    def __sub__(self, other):
        return self._binary(other, lambda left, right: left - right, "-")

    def __rsub__(self, other):
        return _as_coordinate_expression(other).__sub__(self)

    def __mul__(self, other):
        return self._binary(other, lambda left, right: left * right, "*")

    def __rmul__(self, other):
        return _as_coordinate_expression(other).__mul__(self)

    def __neg__(self):
        return CoordinateExpression(
            lambda values: -self.evaluate(values),
            self.coordinates,
            f"-{self!s}",
        )


@dataclass(frozen=True, slots=True)
class Coordinate(_CoordinateArithmetic):
    """One finite retained-space occupation coordinate."""

    name: str
    values: tuple[int, ...]

    @property
    def coordinates(self) -> tuple[Coordinate, ...]:
        """Return this coordinate as a one-item dependency tuple."""
        return (self,)

    def evaluate(self, values: Mapping[Coordinate, int]) -> int:
        """Read this coordinate from a retained state."""
        return values[self]

    def __str__(self) -> str:
        """Return the coordinate name."""
        return self.name


@dataclass(frozen=True, slots=True)
class CoordinateExpression(_CoordinateArithmetic):
    """An integer expression in finite retained-space coordinates."""

    function: Callable[[Mapping[Coordinate, int]], int]
    coordinates: tuple[Coordinate, ...]
    text: str

    def evaluate(self, values: Mapping[Coordinate, int]) -> int:
        """Evaluate the coordinate expression."""
        return int(self.function(values))

    def __str__(self) -> str:
        """Return the expression used to construct this coordinate."""
        return self.text


def _as_coordinate_expression(value: int | _CoordinateArithmetic):
    if isinstance(value, _CoordinateArithmetic):
        return value
    integer = int(value)
    return CoordinateExpression(lambda _values: integer, (), str(integer))


def _unique(values: Iterable[Any]) -> tuple[Any, ...]:
    return tuple(dict.fromkeys(values))


def levels(names: str | Sequence[str], size: int):
    """Create finite occupation coordinates, following ``sympy.symbols`` style."""
    if size <= 0:
        raise ValueError("size must be positive")
    symbols = sympy.symbols(names)
    if isinstance(symbols, sympy.Symbol):
        return Coordinate(str(symbols), tuple(range(size)))
    return tuple(Coordinate(str(symbol), tuple(range(size))) for symbol in symbols)


@dataclass(frozen=True)
class FiniteSpace:
    """Finite product space generated by occupation coordinates."""

    coordinates: tuple[Coordinate, ...]

    @cached_property
    def states(self) -> tuple[OccupationState, ...]:
        """Enumerate states in product order when materialization is requested."""
        return tuple(product(*(coordinate.values for coordinate in self.coordinates)))

    @cached_property
    def index(self) -> dict[OccupationState, int]:
        """Map retained states to matrix indices."""
        return {state: index for index, state in enumerate(self.states)}

    @property
    def dimension(self) -> int:
        """Return the finite Hilbert-space dimension."""
        return len(self.states)


def _operator_sort_key(operator) -> tuple[int, str]:
    return generator_types.index(type(operator)), str(operator.name)


class OccupationEmbedding:
    """Embed finite retained occupations into source Fock occupations."""

    def __init__(
        self,
        occupations: Mapping[object, int | _CoordinateArithmetic],
    ):
        """Compile a target-to-source occupation map."""
        if not occupations:
            raise ValueError("An occupation embedding may not be empty")
        self.operators = tuple(sorted(occupations, key=_operator_sort_key))
        self._expressions = {
            operator: _as_coordinate_expression(value)
            for operator, value in occupations.items()
        }
        coordinates = _unique(
            coordinate
            for value in occupations.values()
            for coordinate in _as_coordinate_expression(value).coordinates
        )
        self.target = FiniteSpace(coordinates)

    def encode(self, state: OccupationState) -> OccupationState:
        """Return the source occupation state corresponding to a retained state."""
        state = tuple(state)
        if len(state) != len(self.target.coordinates):
            raise ValueError("Retained state has the wrong number of coordinates")
        values = dict(zip(self.target.coordinates, state, strict=True))
        if any(
            value not in coordinate.values
            for coordinate, value in zip(self.target.coordinates, state, strict=True)
        ):
            raise ValueError(f"State {state} lies outside the retained basis")
        return tuple(
            self._expressions[operator].evaluate(values) for operator in self.operators
        )


@dataclass(frozen=True)
class FermionSpace:
    """A retained Fock space generated by named fermion modes."""

    modes: tuple[FermionOp, ...]
    numbers: frozenset[int] | None = None

    @cached_property
    def states(self) -> tuple[OccupationState, ...]:
        """Enumerate occupation states when materialization is requested."""
        states = product((0, 1), repeat=len(self.modes))
        if self.numbers is None:
            return tuple(states)
        return tuple(state for state in states if sum(state) in self.numbers)

    @cached_property
    def index(self) -> dict[OccupationState, int]:
        """Map retained states to matrix indices."""
        return {state: index for index, state in enumerate(self.states)}

    @property
    def dimension(self) -> int:
        """Return the retained-space dimension."""
        return len(self.states)


class FermionEmbedding:
    """Embed target fermionic generators into source fermion modes.

    Each source mode is fixed empty/occupied or identified with one retained
    fermion.  The resulting target algebra remains second quantized.
    """

    def __init__(
        self,
        modes: Mapping[FermionOp, FermionOp | int],
        *,
        number: int | Iterable[int] | None = None,
    ):
        """Compile the direct fermion embedding and optional number sector."""
        if not modes:
            raise ValueError("A fermion embedding may not be empty")
        if not all(isinstance(mode, FermionOp) for mode in modes):
            raise TypeError("All source generators must be fermions")
        if not all(
            isinstance(value, FermionOp) or value in (0, 1) for value in modes.values()
        ):
            raise TypeError("Source fermions map to a target fermion, zero, or one")

        self.operators = tuple(sorted(modes, key=_operator_sort_key))
        self._modes = dict(modes)
        target_modes = tuple(
            self._modes[source]
            for source in self.operators
            if isinstance(self._modes[source], FermionOp)
        )
        if len(target_modes) != len(set(target_modes)):
            raise ValueError("Each target fermion must map to one source mode")
        occupied_fixed = 0
        fixed_before = {}
        for source in self.operators:
            target = self._modes[source]
            if isinstance(target, FermionOp):
                fixed_before[target] = occupied_fixed
            elif target == 1:
                occupied_fixed += 1
        self._fixed_before = fixed_before
        if number is None:
            numbers = None
        elif isinstance(number, int):
            numbers = frozenset((number,))
        else:
            numbers = frozenset(number)
        if numbers is not None and any(
            value < 0 or value > len(target_modes) for value in numbers
        ):
            raise ValueError("A target particle number lies outside the Fock space")
        self.target = FermionSpace(target_modes, numbers)


OperatorEmbedding: TypeAlias = OccupationEmbedding | FermionEmbedding


def occupation_embedding(
    occupations: Mapping[object, int | _CoordinateArithmetic],
) -> OccupationEmbedding:
    """Construct a finite occupation embedding."""
    return OccupationEmbedding(occupations)


def fermion_embedding(
    modes: Mapping[FermionOp, FermionOp | int],
    *,
    number: int | Iterable[int] | None = None,
) -> FermionEmbedding:
    """Construct a direct source-to-target fermion embedding."""
    return FermionEmbedding(modes, number=number)
