image: mambaorg/micromamba:1.5.6-jammy

cache:
  paths:
  - micromamba
  - .pre-commit-cache
before_script:
  - mkdir -p micromamba
  - export MAMBA_ROOT_PREFIX=micromamba
  - micromamba create -yf environment.yml
  - eval "$(micromamba shell hook --shell bash)"
  - git config --global --add safe.directory $CI_PROJECT_DIR
variables:
  PRE_COMMIT_HOME: $CI_PROJECT_DIR/.pre-commit-cache


run tests:
  script:
    - pip install pytest-cov pytest-randomly pytest-repeat pytest-ruff
    - py.test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

run nox:
  variables:
    GIT_STRATEGY: clone
    CONDA_PKGS_DIRS: micromamba/pkgs
  parallel:
    matrix:
      - NOXSESSION:
        - "tests(minimal)"
        - "tests(mid)"
        - "tests(latest)"
        - "tests_without_kwant"
  before_script:
    - micromamba install -c conda-forge -r micromamba_root -y mamba pip nox git
  script:
    - nox -s $NOXSESSION
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - micromamba

run docs:
  script:
    - pip install sphinx myst-nb sphinx-togglebutton sphinx-tippy sphinx-copybutton "sphinx-book-theme>=1.1.0"
    - pip install --editable .
    - make -C docs/ html SPHINXOPTS="-WT --keep-going -n"
  artifacts:
    paths:
      - docs/build

run pre-commit:
  script:
    - pre-commit run --all-files

pages:
  needs:
    - run tests
    - run docs
  script:
    - cp -r htmlcov public/
    - cp -r docs/build public/
  artifacts:
    paths:
      - public
