image: gitlab.kwant-project.org:5005/qt/research-docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  EXEC_TIMEOUT: 180

before_script:
  - shopt -s nullglob  # sane behaviour when globs do not match

.pdf-build:
  script:
    - cd $CWD
    - if [ -d images ]; then
    -   cd images
    -   for image in *.svg; do
    -     inkscape -Dz --export-pdf="${image%.*}" $image
    -   done
    -   cd ..
    -  fi
    - for tex in *.tex; do
    -   if grep "documentclass" $tex >/dev/null; then
    -     latexmk -pdf $tex
    -   fi
    - done

run tests:
  script:
    - pip install pytest-cov pytest-randomly pytest-repeat
    - py.test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  extends: .pdf-build
  variables:
    CWD: notes
  needs:
    - run tests
  after_script:
    - mkdir public
    - cp notes/*.pdf public
    - cp -r htmlcov public/
  artifacts:
    paths:
      - public
