image: mambaorg/micromamba:1.4.3

before_script:
  - mkdir -p micromamba
  - export MAMBA_ROOT_PREFIX=micromamba
  - micromamba create -yf docs/environment.yml
  - eval "$(micromamba shell hook --shell bash)"
  - micromamba activate pymablock-docs

run tests:
  # Needed because of coverage reports
  script:
    - pip install pytest-cov pytest-randomly pytest-repeat pytest-ruff pytest-regressions
    - py.test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - micromamba

run nox:
  variables:
    GIT_STRATEGY: clone
    CONDA_PKGS_DIRS: micromamba/pkgs
  parallel:
    matrix:
      - NOXSESSION:
        - "tests(minimal)"
        - "tests(mid)"
        - "tests(latest)"
  script:
    - micromamba install -c conda-forge -y nox mamba
    - nox -s $NOXSESSION
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - micromamba

run docs:
  script:
    - make -C docs/ html SPHINXOPTS="-WT --keep-going -n"
  artifacts:
    paths:
      - docs/build
  cache:
    key: "$CI_JOB_NAME"
    paths:
        - micromamba

run pre-commit:
  variables:
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.pre-commit-cache
  script:
    - micromamba install -c conda-forge -y mamba pip pre-commit git
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - pre-commit run --all-files
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .pre-commit-cache
      - micromamba

paper:
  image: gitlab.kwant-project.org:5005/qt/research-docker
  when: manual
  before_script: []
  script:
    - pip install -e .
    - cd paper/code_figures
    - jupytext --to ipynb --execute *.py
    - cd ../figures
    - for image in *.svg; do
    - inkscape --batch-process -o "${image%.*}.pdf" $image
    - done
    - cd ..
    - sed -i -e "s/\\\usepackage{minted}/\\\usepackage\[finalizecache,cachedir=minted-cache\]{minted}/g" paper.tex
    - for tex in *.tex; do
    - if grep "documentclass" $tex >/dev/null; then
    - latexmk -pdf $tex -shell-escape
    - fi
    - done
  artifacts:
    paths:
      - paper/paper.pdf
      - paper/figures/*.pdf
      - paper/*.bbl
      - paper/minted-cache/*

pages:
  before_script: []
  needs:
    - run tests
    - run docs
    # - paper  # Disabled after finishing the manuscript
  script:
    - mkdir public
    - cp -r htmlcov public/
    - cp -r docs/build public/
    # - cp -r paper/ public/
  artifacts:
    paths:
      - public

prepare zips:
  image: gitlab.kwant-project.org:5005/qt/research-docker
  before_script: []
  when: manual
  needs: [paper]
  script:
    - zip -r zenodo.zip *
    - cd paper
    - sed -i -e "s/\\\today/$(date +'%B %e, %Y')/g" *.tex
    - sed -i -e "s/\\\usepackage{minted}/\\\usepackage\[frozencache,cachedir=minted-cache\]{minted}/g" paper.tex
    - zip ../arxiv.zip *.tex *.bbl figures/*.pdf *.cls *.bst minted-cache/*
  artifacts:
    paths:
      - arxiv.zip
      - zenodo.zip

publish to test pypi:
  needs:
    - run tests
    - run docs
    - run nox
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*\+test$/' # vX.Y.Z.post1+test
  script:
    - micromamba install -c conda-forge -y hatch hatch-vcs
    - hatch build
    - hatch publish -u __token__ -a $PYPI_TEST_TOKEN -r test

publish to pypi:
  needs:
    - run tests
    - run docs
    - run nox
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+[^+]*$/' # No +test
  script:
    - micromamba install -c conda-forge -y hatch hatch-vcs
    - hatch build
    - hatch publish -u __token__ -a $PYPI_TOKEN

test ruff:
  script:
    - pip install ruff
    - ruff check . --fix
