image: mambaorg/micromamba:1.4.3

cache:
  paths:
    - micromamba
before_script:
  - mkdir -p micromamba
  - export MAMBA_ROOT_PREFIX=micromamba
  - micromamba create -yf environment.yml
  - eval "$(micromamba shell hook --shell bash)"
  - micromamba activate env

run tests:
  script:
    - pip install pytest-cov pytest-randomly pytest-repeat pytest-ruff
    - py.test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

run nox:
  variables:
    GIT_STRATEGY: clone
  parallel:
    matrix:
      - NOXSESSION:
        - "tests(minimal)"
        - "tests(mid)"
        - "tests(latest)"
        - "tests_without_kwant"
  before_script:
    - micromamba install -c conda-forge -y mamba pip nox git
  script:
    - nox -s $NOXSESSION
  cache:
    key: "$CI_JOB_NAME"

run docs:
  script:
    - pip install sphinx myst-nb sphinx-togglebutton sphinx-tippy sphinx-copybutton "sphinx-book-theme>=1.1.0"
    - pip install --editable .
    - make -C docs/ html SPHINXOPTS="-WT --keep-going -n"
  artifacts:
    paths:
      - docs/build

run pre-commit:
  before_script:
    - micromamba install -c conda-forge -y mamba pip pre-commit git
    - git config --global --add safe.directory $CI_PROJECT_DIR
  variables:
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.pre-commit-cache
  script:
    - pre-commit run --all-files
  cache:
    paths:
      - .pre-commit-cache

pages:
  needs:
    - run tests
    - run docs
  script:
    - cp -r htmlcov public/
    - cp -r docs/build public/
  artifacts:
    paths:
      - public
