image: gitlab.kwant-project.org:5005/qt/research-docker

before_script:
  - shopt -s nullglob  # sane behaviour when globs do not match

run tests:
  script:
    - pip install pytest-cov pytest-randomly pytest-repeat pytest-ruff
    - py.test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

run nox:
  variables:
    GIT_STRATEGY: clone
    CONDA_PKGS_DIRS: micromamba_root/pkgs
  parallel:
    matrix:
      - NOXSESSION:
        - "tests(minimal)"
        - "tests(mid)"
        - "tests(latest)"
        - "tests_without_kwant"
  before_script:
    - micromamba install -c conda-forge -r micromamba_root -y mamba pip nox git
  script:
    - export MAMBA_ROOT_PREFIX="micromamba_root"; nox -s $NOXSESSION
  image: "mambaorg/micromamba:1.4.3"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - micromamba_root

run docs:
  script:
    - pip install sphinx myst-nb sphinx-togglebutton sphinx-tippy sphinx-copybutton "sphinx-book-theme>=1.1.0"
    - pip install --editable .
    - make -C docs/ html SPHINXOPTS="-WT --keep-going -n"
  artifacts:
    paths:
      - docs/build

pages:
  needs:
    - run tests
    - run docs
  script:
    - cp -r htmlcov public/
    - cp -r docs/build public/
  artifacts:
    paths:
      - public
