image: gitlab.kwant-project.org:5005/qt/research-docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  EXEC_TIMEOUT: 180

before_script:
  - shopt -s nullglob  # sane behaviour when globs do not match

run tests:
  script:
    - pip install pytest-cov pytest-randomly pytest-repeat pytest-ruff
    - py.test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

run nox:
  script:
    - pip install nox
    - nox

run docs:
  script:
    - pip install sphinx sphinx-book-theme myst-nb
    - pip install --editable .
    - make -C docs/ html
  artifacts:
    paths:
      - docs/build
