image: gitlab.kwant-project.org:5005/qt/research-docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  EXEC_TIMEOUT: 180

before_script:
  - shopt -s nullglob  # sane behaviour when globs do not match
  - pip install gitlab-ci-tools  # for last-good-build
  - LAST_GOOD_SHA=$(last-good-build || echo '')

.pdf-build:
  script:
    - cd $CWD
    - if [ -d images ]; then
    -   cd images
    -   for image in *.svg; do
    -     inkscape -Dz --export-pdf="${image%.*}" $image
    -   done
    -   cd ..
    -  fi
    - for tex in *.tex; do
    -   if grep "documentclass" $tex >/dev/null; then
    -     latexmk -pdf $tex
    -     DIFF="$(git diff $LAST_GOOD_SHA -- $tex || echo '')"
    -     if [ "$LAST_GOOD_SHA" ] && [ "$DIFF" ]; then
    -       git show $LAST_GOOD_SHA:$CWD/$tex > old_$tex
    -       latexdiff old_$tex $tex > diff_$tex
    -       rm old_$tex
    -       latexmk -pdf diff_$tex
    -     fi
    -   fi
    - done

run tests:
  script:
    - pip install pytest-cov
    - py.test codes/tests/ --cov=codes --verbose --cov-report html --cov-report term
  artifacts:
    paths:
      - htmlcov

pages:
  extends: .pdf-build
  variables:
    CWD: notes
  needs:
    - run tests
  after_script:
    - mkdir public
    - cp notes/*.pdf public
    - cp -r htmlcov public/
  artifacts:
    paths:
      - public
