image: rafalskolasinski/science:latest

stages:
  - run analysis
  - build documents

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ENVIRONMENT: /opt/conda/envs/kwant
  EXEC_TIMEOUT: 180

before_script:
  - shopt -s nullglob  # sane behaviour when globs do not match
  - pip install gitlab-ci-tools  # for last-good-build
  - LAST_GOOD_SHA=$(last-good-build || echo '')

run analysis:
  script:
    - $ENVIRONMENT/bin/pip install git+https://gitlab.kwant-project.org/semicon/semicon.git
    - $ENVIRONMENT/bin/python -m ipykernel install --user --name run_env
    - cd analysis
    - for ipynb in *.ipynb; do
    -    jupyter nbconvert --ExecutePreprocessor.kernel_name=run_env --to notebook --execute "$ipynb" --output "$ipynb" --ExecutePreprocessor.timeout=$EXEC_TIMEOUT
    - done
  artifacts:
    paths:
      - analysis/*.ipynb
    expire_in: 1 month
  stage: run analysis


.pdf-build: &pdf_build
  stage: build documents
  script:
    - cd $CWD
    - if [ -d images ]; then
    -   cd images
    -   for image in *.svg; do
    -     inkscape -Dz --export-pdf="${image%.*}" $image
    -   done
    -   cd ..
    -  fi
    - for tex in *.tex; do
    -   if grep "documentclass" $tex >/dev/null; then
    -     latexmk -pdf $tex
    -     DIFF="$(git diff $LAST_GOOD_SHA -- $tex || echo '')"
    -     if [ "$LAST_GOOD_SHA" ] && [ "$DIFF" ]; then
    -       git show $LAST_GOOD_SHA:$CWD/$tex > old_$tex
    -       latexdiff old_$tex $tex > diff_$tex
    -       rm old_$tex
    -       latexmk -pdf diff_$tex
    -     fi
    -   fi
    - done

build notes:
  <<: *pdf_build
  variables:
    CWD: notes
  artifacts:
    paths:
      - notes/notes.pdf
      - notes/diff_notes.pdf
    expire_in: 1 month

build publication:
  <<: *pdf_build
  variables:
    CWD: publication
  artifacts:
    paths:
      - publication/*.pdf
    expire_in: 1 month
  stage: build documents
