name = "pymablock_formalization"
version = "0.1.0"
defaultTargets = ["Pymablock"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.29.0"

[[lean_lib]]
name = "Pymablock"
